# Site settings
title: Creolophus的博客
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'your-disqus-name'

author:
  name: 'Creolophus'
  email: civilian0304@gmail.com
  twitter_username: creolophus2
  # facebook_username: joshgerdes
  github_username:  Creolophus
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      # path: 'Jekyll-Uno
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
